name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: msbuild $Env:GITHUB_WORKSPACE\QuestEyes-Server.sln -t:rebuild -verbosity:diag -property:Configuration=Release
