name: Build Web App
 
on: [push]
 
jobs:
  build:
 
    strategy:
      matrix:
        targetplatform: [x86, x64]
        
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
 
    - name: Build App
      run: msbuild QuestEyes-Server\QuestEyes-Server.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      env:
        Configuration: Debug
        RuntimeIdentifier: win-${{ matrix.targetplatform }}
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: built_app
        path: bin\Release\net5.0-windows\publish\
